site_name: MolTopolParser
site_url: http://moltopolparser.bocores.com

theme:
   name: 'material'
   palette:
        primary: 'indigo'

nav:
  - Getting Started: index.md
  - Install: install.md
  - Example: example.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

# mkdocs serve
# mkdocs deploy 
